name: validate-pr

on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}.${{ github.sha }}.validate-pr
  cancel-in-progress: true

jobs:
  premerge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            tools:
              - 'tools/js/**'
              - 'tools/ts/**'
              - 'tools/*.json'
              - 'tsconfig*'
              - '.eslint*'
              - '.prettier*'
            dependencies:
              - 'package.json'
              - 'yarn.lock'
            shelltools:
              - 'tools/shell/**'

      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Validate the commit messages
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        run: |
          git checkout -b premerge
          git fetch origin main:main
          npx --no-install commitlint --from main

      - name: Lint tools (eslint)
        if: ${{ steps.changes.outputs.tools == 'true' || steps.changes.outputs.dependencies == 'true' }}
        run: yarn lint

      - name: Lint shell
        if: steps.changes.outputs.shelltools == 'true'
        run: |
          sudo apt install shellcheck
          yarn lint:shell
